<?php

/**
 * @file
 * Allows SSH keys to be associated with entities.
 */

/**
 * Return value for hook_sshkey_access() to allow access to an SSH key.
 */
define('SSHKEY_ACCESS_ALLOW', 'allow');

/**
 * Return value for hook_sshkey_access() to deny access to a SSH key.
 */
define('SSHKEY_ACCESS_DENY', 'deny');

/**
 * Return value for hook_sshkey_access() to not affect SSH key access.
 */
define('SSHKEY_ACCESS_IGNORE', NULL);

/**
 * Exception thrown if a public key does not parse correctly.
 */
class SSHKeyParseException extends Exception { }

/**
 * Implements hook_entity_info().
 */
function sshkey_entity_info() {
  $info['sshkey'] = array(
    'label' => t('SSH Key'),
    'base table' => 'sshkey',
    'entity keys' => array(
      'id' => 'key_id',
      'label' => 'title',
    ),
    'fieldable' => FALSE,
  );

  return $info;
}

/**
 * Implements hook_config_info().
 */
function sshkey_config_info() {
  $prefixes['sshkey.settings'] = array(
    'label' => t('SSH public keys settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_permission().
 */
function sshkey_permission() {
  $perm = array(
    'view any SSH public keys' => array(
      'title' => t('View any SSH public keys'),
    ),
    'view own SSH public keys' => array(
      'title' => t('View own SSH public keys'),
    ),
    'edit any SSH public keys' => array(
      'title' => t('Edit any SSH public keys'),
      'restrict access' => TRUE,
    ),
    'edit own SSH public keys' => array(
      'title' => t('Edit own SSH public keys'),
    ),
    'manage any SSH public keys' => array(
      'title' => t('Create and delete any SSH public keys'),
      'restrict access' => TRUE,
    ),
    'manage own SSH public keys' => array(
      'title' => t('Create and delete own SSH public keys'),
    ),
    'administer SSH public keys' => array(
      'title' => t('Administer SSH public keys'),
      'restrict access' => TRUE,
    ),
  );
  return $perm;
}

/**
 * Implements hook_menu().
 */
function sshkey_menu() {
  $items['user/%/ssh-keys'] = array(
    'title' => 'SSH keys',
    'page callback' => 'sshkey_list_page',
    'page arguments' => array('user', 1),
    'access callback' => 'sshkey_access',
    'access arguments' => array('view', 'user', 1),
    'file' => 'sshkey.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  // The first two arguments for the following CRUD pages are entity type,
  // followed by entity ID.
  $items['ssh-keys/%/%/add'] = array(
    'title' => 'Add a SSH key',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('sshkey_edit_form', 1, 2),
    'access callback' => 'sshkey_access',
    'access arguments' => array('create', 1, 2),
    'file' => 'sshkey.pages.inc',
    'modal' => TRUE,
  );
  $items['ssh-keys/%/%/%sshkey/view'] = array(
    'title' => 'View SSH key',
    'page callback' => 'sshkey_view_key',
    'page arguments' => array(1, 2, 3),
    'access callback' => 'sshkey_access',
    'access arguments' => array('view', 1, 2, 3),
    'file' => 'sshkey.pages.inc',
  );
  $items['ssh-keys/%/%/%sshkey/edit'] = array(
    'title' => 'Edit SSH key',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('sshkey_edit_form', 1, 2, 3),
    'access callback' => 'sshkey_access',
    'access arguments' => array('edit', 1, 2, 3),
    'file' => 'sshkey.pages.inc',
    'modal' => TRUE,
  );
  $items['ssh-keys/%/%/%sshkey/delete'] = array(
    'title' => 'Delete SSH key',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('sshkey_delete_form', 3),
    'access callback' => 'sshkey_access',
    'access arguments' => array('delete', 1, 2, 3),
    'file' => 'sshkey.pages.inc',
    'modal' => TRUE,
  );

  $items['admin/config/system/ssh-keys'] = array(
    'title' => 'SSH public key settings',
    'description' => 'Configure the SSH public key settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('sshkey_settings_form'),
    'access arguments' => array('administer SSH public keys'),
    'file' => 'sshkey.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function sshkey_theme($existing, $type, $theme, $path) {
  $info['sshkey_fingerprint'] = array(
    'variables' => array('key' => NULL),
  );
  return $info;
}

/**
 * Implements hook_entity_delete().
 */
function sshkey_entity_delete($entity, $entity_type) {
  if ($entity_type == 'sshkey') {
    return;
  }
  list($id) = entity_extract_ids($entity_type, $entity);
  sshkey_delete_all_by_entity($entity_type, $id);
}

/**
 * Implements hook_views_api().
 */
function sshkey_views_api() {
  return array(
    'api' => 2,
    'path' => backdrop_get_path('module', 'sshkey') . '/views',
  );
}

/**
 * Access callback for SSH public key operations.
 */
function sshkey_access($op, $entity_type = NULL, $entity_id = NULL, $key = NULL, $account = NULL) {
  $rights = &backdrop_static(__FUNCTION__, array());

  if (!in_array($op, array('view', 'create', 'edit', 'delete'), TRUE)) {
    // If $op was not one of the supported ones, we return access denied.
    return FALSE;
  }

  // Default user_access() checks to use the current user.
  if (!isset($account)) {
    $account = $GLOBALS['user'];
  }

  $cid = is_object($key) ? $key->key_id : 0;

  // Make sure the entity type and IDs match the existing key's entity data.
  if (is_object($key)) {
    if (isset($entity_type) && $key->entity_type != $entity_type) {
      return FALSE;
    }
    elseif (isset($entity_id) && $key->entity_id != $entity_id) {
      return FALSE;
    }
  }

  // Make sure that an actual entity object exists to attach to.
  if (!entity_load($entity_type, array($entity_id))) {
    return FALSE;
  }

  // If we've already checked access for this key, user and op, return from
  // cache.
  if (isset($rights[$account->uid][$cid][$op])) {
    return $rights[$account->uid][$cid][$op];
  }

  // Admins can do everything.
  if (user_access('administer SSH public keys', $account)) {
    $rights[$account->uid][$cid][$op] = TRUE;
    return TRUE;
  }

  // We grant access to the key if both of the following conditions are met:
  // - No modules say to deny access.
  // - At least one module says to grant access.
  $access = module_invoke_all('sshkey_access', $op, $entity_type, $entity_id, $key, $account);
  if (in_array(SSHKEY_ACCESS_DENY, $access, TRUE)) {
    $rights[$account->uid][$cid][$op] = FALSE;
    return FALSE;
  }
  elseif (in_array(SSHKEY_ACCESS_ALLOW, $access, TRUE)) {
    $rights[$account->uid][$cid][$op] = TRUE;
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_sshkey_access().
 */
function sshkey_sshkey_access($op, $entity_type, $entity_id, $key, $account) {
  if ($op == 'view') {
    if (user_access('view any SSH public keys')) {
      return SSHKEY_ACCESS_ALLOW;
    }
    else {
      $entity = entity_load($entity_type, array($entity_id));
      $entity = reset($entity);
      if (isset($entity->uid) && $entity->uid == $account->uid && user_access('view own SSH public keys')) {
        return SSHKEY_ACCESS_ALLOW;
      }
    }
  }
  elseif ($op == 'edit') {
    if (user_access('edit any SSH public keys')) {
      return SSHKEY_ACCESS_ALLOW;
    }
    else {
      $entity = entity_load($entity_type, array($entity_id));
      $entity = reset($entity);
      if (isset($entity->uid) && $entity->uid == $account->uid && user_access('edit own SSH public keys')) {
        return SSHKEY_ACCESS_ALLOW;
      }
    }
  }
  else {
    if (user_access('manage any SSH public keys')) {
      return SSHKEY_ACCESS_ALLOW;
    }
    else {
      $entity = entity_load($entity_type, array($entity_id));
      $entity = reset($entity);
      if (isset($entity->uid) && $entity->uid == $account->uid && user_access('manage own SSH public keys')) {
        return SSHKEY_ACCESS_ALLOW;
      }
    }
  }

  return SSHKEY_ACCESS_IGNORE;
}

/**
 * Load an SSH public key and optionally by entity type and ID.
 */
function sshkey_load($key_id, $reset = FALSE) {
  $keys = entity_load('sshkey', array($key_id), array(), $reset);
  return !empty($keys)?reset($keys) : FALSE;
}

/**
 * Load an SSH public key by fingerprint.
 */
function sshkey_load_by_fingerprint($fingerprint) {
  $keys = entity_load('sshkey', FALSE, array('fingerprint' => $fingerprint));
  return !empty($keys)?reset($keys) : FALSE;
}

/**
 * Load all SSH public keys associated with an entity.
 */
function sshkey_load_all_by_entity($entity_type, $entity_id) {
  return entity_load('sshkey', FALSE, array('entity_type' => $entity_type, 'entity_id' => $entity_id));
}

/**
 * Load multiple SSH public keys.
 */
function sshkey_load_multiple($key_ids = array(), array $conditions = array(), $reset = FALSE) {
  return entity_load('sshkey', $key_ids, $conditions, $reset);
}

/**
 * Save a SSH public key.
 */
function sshkey_save($key) {
  $transaction = db_transaction();

  try {
    if (!empty($key->key_id) && !isset($key->original)) {
      $key->original = entity_load_unchanged('sshkey', $key->key_id);
    }

    // Determine if we will be inserting a new node.
    if (!isset($key->is_new)) {
      $key->is_new = empty($key->key_id);
    }

    // The changed timestamp is always updated for bookkeeping purposes.
    $key->changed = time();

    if (!isset($key->entity_type) && !isset($key->entity_id)) {
      $key->entity_type = 'user';
      $key->entity_id = $GLOBALS['user']->uid;
    }

    // Re-fingerprint the key.
    $parsed = sshkey_parse($key->value);
    $key->fingerprint = $parsed['fingerprint'];
    $key->value = $parsed['value'];

    // Add a default name based on public key comment if available.
    if (empty($key->title)) {
      if (isset($parsed['comment'])) {
        $key->title = truncate_utf8($parsed['comment'], 128, TRUE);
      }
      else {
        $key->title = truncate_utf8($key->value, 26, FALSE);
      }
    }

    // Allow other modules to alter the public key before saving.
    module_invoke_all('sshkey_presave', $key);

    // Save the key to the database and invoke the post-save hooks.
    if ($key->is_new) {
      backdrop_write_record('sshkey', $key);
      module_invoke_all('sshkey_insert', $key);
      watchdog('sshkey', 'Added new SSH key %key (@fingerprint).', array('%key' => $key->title, '@fingerprint' => $key->fingerprint));
    }
    else {
      backdrop_write_record('sshkey', $key, array('key_id'));
      module_invoke_all('sshkey_update', $key);
      watchdog('sshkey', 'Updated SSH key %key (@fingerprint).', array('%key' => $key->title, '@fingerprint' => $key->fingerprint));
    }

    // Clear internal properties.
    unset($key->is_new);
    unset($key->original);

    // Clear the static loading cache.
    entity_get_controller('sshkey')->resetCache(array($key->key_id));

    // Ignore slave server temporarily to give time for the
    // saved node to be propagated to the slave.
    db_ignore_slave();
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('sshkey', $e);
    throw $e;
  }
}

/**
 * Delete an SSH public key.
 */
function sshkey_delete($key_ids) {
  return sshkey_delete_multiple(array($key_ids));
}

/**
 * Delete multiple SSH public keys.
 */
function sshkey_delete_multiple($key_ids) {
  if (empty($key_ids)) {
    return;
  }

  $transaction = db_transaction();

  try {
    $keys = sshkey_load_multiple($key_ids);
    foreach ($keys as $key_id => $key) {
      module_invoke_all('sshkey_delete', $key);
      watchdog('sshkey', 'Deleted SSH key %key (@fingerprint).', array('%key' => $key->title, '@fingerprint' => $key->fingerprint));
    }

    db_delete('sshkey')
      ->condition('key_id', $key_ids, 'IN')
      ->execute();

  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('sshkey', $e);
    throw $e;
  }

  // Clear the entity caches.
  entity_get_controller('sshkey')->resetCache();
}

/**
 * Delete all SSH public keys associated with an entity.
 */
function sshkey_delete_all_by_entity($entity_type, $entity_id) {
  $key_ids = db_query("SELECT key_id FROM {sshkey} WHERE entity_type = :entitytype AND entity_id = :entityid", array(':entitytype' => $entity_type, ':entityid' => $entity_id))->fetchCol();
  return !empty($key_ids)?sshkey_delete_multiple($key_ids) : FALSE;
}

/**
 * Validate an SSH public key.
 */
function sshkey_validate($key, $form, &$form_state) {
  $key = (object) $key;

  try {
    $parsed = sshkey_parse($key->value);
    $existing_key = sshkey_load_by_fingerprint($parsed['fingerprint']);
    if (!empty($existing_key->key_id) && $existing_key->key_id != $key->key_id) {
      form_set_error('value', t('The public key with fingerprint %fingerprint is already in use.', array('%fingerprint' => $parsed['fingerprint'])));
    }
  }
  catch (SSHKeyParseException $e) {
    form_set_error('value', $e->getMessage());
    return;
  }

  // Allow other modules to validate the SSH public key.
  foreach (module_implements('sshkey_validate') as $module) {
    $function = $module . '_sshkey_validate';
    $function($key, $form, $form_state, $parsed);
  }
}

/**
 * Parses a SSH public key.
 *
 * @param string $key_raw
 *   The string with the raw SSH public key.
 */
function sshkey_parse($key_raw) {
  $parsed['value'] = sshkey_clean_whitespace($key_raw);

  // The SSH key should be a string in the form:
  // "<algorithm type> <base64-encoded key> <comment>".
  $key_parts = explode(' ', $parsed['value'], 3);
  if (count($key_parts) < 2) {
    throw new SSHKeyParseException(t('The key is invalid. It does not match the expected format.'));
  }

  $parsed['algorithm'] = $key_parts[0];
  $algorithms = array(
    "ssh-rsa",
    "ssh-dss",
    "ssh-ed25519",
  );
  if (!in_array($parsed['algorithm'], $algorithms)) {
    // Produces a string like "ssh-rsa, ssh-dss, or ssh-ed25519".
    $algorithm_string = implode(', or ', array_merge(
      [implode(', ', array_slice($algorithms, 0, -1))],
      array_slice($algorithms, -1)
    ));
    throw new SSHKeyParseException(t('The key is invalid. It must begin with @algorithms.', ['@algorithms' => $algorithm_string]));
  }

  $parsed['key'] = $key_parts[1];
  // Decode the key, if it is valid base64.
  $key_base64_decoded = base64_decode($parsed['key'], TRUE);
  if ($key_base64_decoded === FALSE) {
    throw new SSHKeyParseException(t('The key could not be decoded.'));
  }
  // Check if the data has okay data.
  $expected_prefix = pack('N', strlen($parsed['algorithm'])) . $parsed['algorithm'];
  if (strpos($key_base64_decoded, $expected_prefix) !== 0) {
    throw new SSHKeyParseException(t('The key is invalid. It is not a public key.'));
  }

  $parsed['fingerprint'] = md5($key_base64_decoded);

  if (isset($key_parts[2])) {
    $parsed['comment'] = $key_parts[2];
  }

  return $parsed;
}

/**
 * Attempt to clean up extra whitespace in the key, before parsing.
 *
 * @param string $key_raw
 *   The raw (provided) key.
 *
 * @return string
 *   A key containing correct whitespace.
 */
function sshkey_clean_whitespace($key_raw) {
  // Replace all consecutive whitespace characters with a single space.
  $key = trim(preg_replace('/\s+/', ' ', $key_raw));

  // Ignore keys that do not contain a space.
  if (strpos($key, ' ') === FALSE) {
    return $key;
  }

  // Split the key type (e.g. 'ssh-rsa') from the rest of the key.
  list($type, $rest) = explode(' ', $key, 2);

  // Go through the space-separated parts of $rest, concatenating them into
  // $value, to create the longest possible base64-encoded string. Any
  // left-over parts will be considered as the key's "comment".
  $value = '';
  $comment = '';
  $parts = explode(' ', $rest);
  foreach ($parts as $index => $part) {
    $valid = $value !== '' && base64_decode($value, TRUE) !== FALSE;
    $valid_next = $value !== '' && base64_decode($value . $part, TRUE) !== FALSE;
    if ($valid && !$valid_next) {
      $comment = implode(' ', array_slice($parts, $index));
      break;
    }
    $value .= $part;
  }

  // If it was not possible to generate any valid base64-encoded string, then
  // return the key with all spaces preserved. The key will probably fail
  // validation.
  if (empty($value)) {
    return $key;
  }

  // A single character appended to a base64 string and extra '=' padding will
  // be ignored by base64_decode(). Re-encode to catch that, and move to the
  // comment.
  $decoded_value = base64_decode($value, TRUE);
  $encoded_value = base64_encode($decoded_value);
  if (strlen($encoded_value) < strlen($value)) {
    if (empty($comment)) {
      $comment = substr($value, strlen($encoded_value));
    }
    else {
      $comment = substr($value, strlen($encoded_value)) . ' ' . $comment;
    }
  }

  // Some of the comment may have been misinterpeted as base64 data. Parse
  // segments from the key and check the lengths. Each segment is the packed
  // unsigned long length, followed by that many bytes.
  $key_value = '';
  $sections = [];
  while (strlen($decoded_value) > 4 && ($expected_length = 4 + unpack('N', $decoded_value) [1]) <= strlen($decoded_value)) {
    $sections[] = substr($decoded_value, 4, $expected_length - 4);
    $key_value .= substr($decoded_value, 0, $expected_length);
    $decoded_value = substr($decoded_value, $expected_length);
  }

  // Check sections to match key formatting.
  $expected_section_count = [
    'ssh-rsa' => 3,
    'ssh-dss' => 5,
    // https://tools.ietf.org/html/draft-bjh21-ssh-ed25519-02#section-4
    'ssh-ed25519' => 2,
    // https://tools.ietf.org/html/rfc5656#section-3.1
    'ecdsa-sha2-nistp256' => 3,
    'ecdsa-sha2-nistp384' => 3,
    'ecdsa-sha2-nistp521' => 3,
  ];
  if (isset($expected_section_count[$type]) && count($sections) !== $expected_section_count[$type]) {
    throw new SSHKeyParseException(t('The key is invalid. It does not have the expected data. Check that the entire key was copied.'));
  }
  if ($type === 'ssh-ed25519' && strlen($sections[1]) !== 32) {
    throw new SSHKeyParseException(t('The key is invalid. It does not have the expected length. Check that the entire key was copied.'));
  }

  $key_value = base64_encode($key_value);

  // The remainder is probably the comment.
  if (strlen($decoded_value) > 0) {
    if (empty($comment)) {
      $comment = substr($value, strlen($key_value));
    }
    else {
      $comment = substr($value, strlen($key_value)) . ' ' . $comment;
    }
  }

  return trim($type . ' ' . $key_value . ' ' . $comment);
}

/**
 * Theme callback to output a formatted SSH key fingerprint.
 */
function theme_sshkey_fingerprint($variables) {
  $key = $variables['key'];
  $chunks = str_split($key->fingerprint, 2);
  return implode(':', $chunks);
}

/**
 * Implements hook_autoload_info().
 */
function sshkey_autoload_info() {
  return array(
    'SSHKeyParseException' => 'sshkey.module',
    'sshkey_handler_field_sshkey_link' => 'views/sshkey_handler_field_sshkey_link.inc',
    'sshkey_handler_field_sshkey_link_delete' => 'views/sshkey_handler_field_sshkey_link_delete.inc',
    'sshkey_handler_field_sshkey_link_edit' => 'views/sshkey_handler_field_sshkey_link_edit.inc',
    'sshkey_handler_field_sshkey_link_view' => 'views/sshkey_handler_field_sshkey_link_view.inc',
    'sshkey_handler_field_sshkey_operations' => 'views/sshkey_handler_field_sshkey_operations.inc',
  );
}
